### ISSUE TITLE
No mechanism to invalidate old store structures in session storage if the application changes.

### ISSUE THREAD

**Issue by VoltiSubito** [mvolkmann/redux-easy#5]
A developer on our project rarely closes his browser.  When he leaves for the day, he just closes the lid and goes home.  This means that sometimes he will open the tab that our application is in, and the browser will (correctly) present him with the session storage from an old version of the app.  If the structure of the store has changed at all, this will likely cause problems.

I think a good solution would be to optionally provide redux-easy with a "version string" when it is initialized.  If the string presented during initialization doesn't match the one stored, the cache should be invalidated.  Alternatively, maybe redux-easy could take the initial state it receives and hash that to determine on it's own if the structure has changed.

**Comment by mvolkmann** [comment]
In the hash approach, would it only hash the initial state? I wonder if that is enough. Perhaps a new version of an app would operate differently based on the actual data in the state. Maybe the current state is in a form that a new version of the app would never allow and that could be problematic even though the initial state did not change.

Your version string idea seems more robust.

**Comment by mvolkmann** [comment]
The options object passed to `reduxSetup` now accepts a `version` property. When the shape of the state needs to change, you can invalidate what is in sessionStorage by changing the version. This will cause the new initialState object to be used. The version can be a number or a string.
