### ISSUE TITLE
how to gradually migrate a large codebase?

### ISSUE THREAD

**Issue by wvlia5** [mvolkmann/redux-easy#7]
Redux apps usually get a gargantuan boilerplate.
As it currently stands, the readme suggests a way of transforming the whole codebase.
I think it would be nice to have some hints of how you could use both simultaneously while migrating, what helper functions start using first, and so on.

**Comment by mvolkmann** [comment]
Yeah, switching state management approaches is bound to be a large amount of work regardless of the previous and new choices. This feels like one of those cases where changing it all at once is best, despite being a lot of work. Working in a code base that uses a mixture of approaches is bound to be confusing. At the moment my favorite way to manage state in React applications is https://www.npmjs.com/package/context-easy.

I have also implemented the same idea for Vue in https://www.npmjs.com/package/vuex-easy.
